apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-crud-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bijuthottathil/Flask-Postgress-K8S.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
